/* CODEHEAL DATABASE */
CREATE SCHEMA IF NOT EXISTS ECOMMERCE;


/* USERS TABLE */
CREATE TABLE users(ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(30) NOT NULL, PHONENUMBER INT NOT NULL, EMAIL VARCHAR(30) NOT NULL,PASSWORD VARCHAR(200) NOT NULL,ADDRESS VARCHAR(100),COUNTRY VARCHAR(20) NOT NULL,RATTINGS INT(1),PROFILEPICTURE VARCHAR(1000), DATE DATETIME NOT NULL);

/* PRODUCT TABLE */
CREATE TABLE products(ID INT AUTO_INCREMENT PRIMARY KEY, PRODUCT VARCHAR(30) NOT NULL, DESCRIPTION VARCHAR(1000) NOT NULL, CATEGORY VARCHAR(50) NOT NULL,PRICE INT NOT NULL,PREVPRICE INT NOT NULL,STOKE INT NOT NULL,COST INT NOT NULL,SERIAL INT , INSERTDATE DATETIME NOT NULL, IMAGE VARCHAR(200));
