/* CODEHEAL DATABASE */
CREATE SCHEMA IF NOT EXISTS ECOMMERCE;


/* USERS TABLE */
CREATE TABLE users(ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(30) NOT NULL, PHONENUMBER INT NOT NULL, EMAIL VARCHAR(30) NOT NULL,PASSWORD VARCHAR(200) NOT NULL,ADDRESS VARCHAR(100),COUNTRY VARCHAR(20) NOT NULL,RATTINGS INT(1),PROFILEPICTURE VARCHAR(1000), DATE DATETIME NOT NULL);

/* USERS TABLE  OPTIMIZATIONS */
CREATE INDEX idx_FullName ON users(FullName);